"""
Django settings for financas_pessoais project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
# financas_pessoais/settings.py
import os
import dj_database_url
from pathlib import Path

# financas_pessoais/settings.py
SECRET_KEY = os.environ.get('SECRET_KEY', 'sua-chave-secreta-local-para-desenvolvimento')

# financas_pessoais/settings.py
# O valor 'RENDER' será uma variável de ambiente que só existirá no servidor do Render.
DEBUG = 'RENDER' not in os.environ

# financas_pessoais/settings.py
ALLOWED_HOSTS = []

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    
    

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)*)iw%(_1ii7fqhhvg=(z8b4^+c539m!$diie8#_#g@p7n)suy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    
    # Aplicações de terceiros
    'rest_framework',  # <<< Certifique-se que esta linha está presente
    'corsheaders',     # <<< Adicione esta linha para o CORS
    'django_filters',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware'
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'financas_pessoais.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'financas_pessoais.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# financas_pessoais/settings.py
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require='RENDER' in os.environ # Ativa SSL apenas no Render
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configurações para CORS (Cross-Origin Resource Sharing)
# ESSENCIAL para permitir que seu frontend React (em uma porta diferente)
# se comunique com sua API Django.
# ----------------------------------------------------
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Porta padrão do Vite para desenvolvimento
    "http://127.0.0.1:5173",  # Alternativa para localhost
    # Se você for rodar o frontend em outro domínio/porta futuramente, adicione aqui:
    # "https://seu-dominio-frontend.com",
]

CORS_ALLOW_CREDENTIALS = True

# Configurações para o Django REST Framework para usar django-filter
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}

# Configurações de Arquivos Estáticos (VERSÃO CORRIGIDA)
STATIC_URL = '/static/'

# Define o local para onde o `collectstatic` irá copiar todos os arquivos estáticos.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Habilita o armazenamento otimizado do WhiteNoise para servir os arquivos.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'