# Generated by Django 5.2.1 on 2025-06-03 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Meta')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('economizar', 'Economizar'), ('investir', 'Investir'), ('abater_divida', 'Abater Dívida'), ('outros', 'Outros')], default='economizar', max_length=20, verbose_name='Tipo de Meta')),
                ('valor_alvo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Alvo')),
                ('valor_atingido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Atingido')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_limite', models.DateField(verbose_name='Data Limite')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Meta Financeira',
                'verbose_name_plural': 'Metas Financeiras',
                'ordering': ['data_limite', '-data_criacao'],
            },
        ),
    ]
