# Generated by Django 5.2.1 on 2025-06-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo_categoria',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('ambos', 'Ambos')], default='despesa', max_length=10, verbose_name='Tipo de Categoria'),
        ),
    ]
